site_name: Aruna Object Storage Documentation
site_url: https://ArunaStorage.github.io/Documentation

repo_name: 'ArunaStorage/Documentation'
repo_url: 'https://github.com/ArunaStorage/Documentation'

docs_dir: docs/

nav:
  - 'Home': index.md

theme:
  name: material
  logo: assets/logo-claim.png
  favicon: assets/logo-icon.png
  features:
    - navigation.tabs
    - navigation.sections  # Sections are included in the navigation on the left.
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox
  - search
