site_name: Aruna Object Storage Documentation
site_url: https://ArunaStorage.github.io/Documentation

repo_name: 'ArunaStorage/Documentation'
repo_url: 'https://github.com/ArunaStorage/Documentation'

docs_dir: docs/

nav:
  - 'Home': index.md
  - 'Get Started':
      - 'Overview': get_started/basic_usage/00_index.md
      - 'Get Storage Access': get_started/basic_usage/01_Get-Storage-Access.md
      - 'Authorization/Tokens': get_started/basic_usage/02_How-To-Auth-Tokens.md
      - 'Projects': get_started/basic_usage/03_How-To-Project.md

theme:
  name: material
  logo: assets/logo-claim.png
  favicon: assets/logo-icon.png
  features:
    - navigation.tabs
    - navigation.sections  # Sections are included in the navigation on the left.
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox
  - search
